apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: app1
spec:
  labels:
    intent: app1
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [ "t3a.medium" ] 
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    # - key: "topology.kubernetes.io/zone"
    #   operator: In
    #   values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64","arm64"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  taints:
  - effect: NoSchedule
    key: app1
  providerRef:
    name: app1
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: app1
spec:
  amiFamily: Bottlerocket
  subnetSelector:
      karpenter.sh/discovery:   "karpenter"
  securityGroupSelector:
      karpenter.sh/discovery:   "karpenter"
  tags:
    KarpenerProvisionerName: "app1"
    NodeType: "karpenter-workshop"
    IntentLabel: "app1"
  userData:  |
    [settings.kubernetes]
    kube-api-qps = 30
    [settings.kubernetes.eviction-hard]
    "memory.available" = "20%"